# ai query: Can you make me an Ansible playbook to install IntelliJ Idea Community Edition on Ubuntu Linux?

- name: Install snap: IntelliJ IDEA Community Edition
  community.general.snap:
    name:
      - intellij-idea-community
    classic: true
  become: true